/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RReportIdRouteImport } from './routes/r.$reportId'
import { Route as ApiFounderTranscribeRouteImport } from './routes/api/founder-transcribe'
import { Route as AuthenticatedXrayRouteImport } from './routes/_authenticated/xray'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductStrategyRouteImport } from './routes/_authenticated/product-strategy'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFounderReadinessRouteImport } from './routes/_authenticated/founder-readiness'
import { Route as AuthenticatedFounderGpsRouteImport } from './routes/_authenticated/founder-gps'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedReportReportIdRouteImport } from './routes/_authenticated/report.$reportId'
import { Route as AuthenticatedProductStrategyStrategyIdRouteImport } from './routes/_authenticated/product-strategy.$strategyId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RReportIdRoute = RReportIdRouteImport.update({
  id: '/r/$reportId',
  path: '/r/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFounderTranscribeRoute = ApiFounderTranscribeRouteImport.update({
  id: '/api/founder-transcribe',
  path: '/api/founder-transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedXrayRoute = AuthenticatedXrayRouteImport.update({
  id: '/xray',
  path: '/xray',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductStrategyRoute =
  AuthenticatedProductStrategyRouteImport.update({
    id: '/product-strategy',
    path: '/product-strategy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderReadinessRoute =
  AuthenticatedFounderReadinessRouteImport.update({
    id: '/founder-readiness',
    path: '/founder-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFounderGpsRoute = AuthenticatedFounderGpsRouteImport.update({
  id: '/founder-gps',
  path: '/founder-gps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportReportIdRoute =
  AuthenticatedReportReportIdRouteImport.update({
    id: '/report/$reportId',
    path: '/report/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductStrategyStrategyIdRoute =
  AuthenticatedProductStrategyStrategyIdRouteImport.update({
    id: '/$strategyId',
    path: '/$strategyId',
    getParentRoute: () => AuthenticatedProductStrategyRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founder-gps': typeof AuthenticatedFounderGpsRoute
  '/founder-readiness': typeof AuthenticatedFounderReadinessRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/product-strategy': typeof AuthenticatedProductStrategyRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/xray': typeof AuthenticatedXrayRoute
  '/api/founder-transcribe': typeof ApiFounderTranscribeRoute
  '/r/$reportId': typeof RReportIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/product-strategy/$strategyId': typeof AuthenticatedProductStrategyStrategyIdRoute
  '/report/$reportId': typeof AuthenticatedReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founder-gps': typeof AuthenticatedFounderGpsRoute
  '/founder-readiness': typeof AuthenticatedFounderReadinessRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/product-strategy': typeof AuthenticatedProductStrategyRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/xray': typeof AuthenticatedXrayRoute
  '/api/founder-transcribe': typeof ApiFounderTranscribeRoute
  '/r/$reportId': typeof RReportIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/product-strategy/$strategyId': typeof AuthenticatedProductStrategyStrategyIdRoute
  '/report/$reportId': typeof AuthenticatedReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/founder-gps': typeof AuthenticatedFounderGpsRoute
  '/_authenticated/founder-readiness': typeof AuthenticatedFounderReadinessRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/product-strategy': typeof AuthenticatedProductStrategyRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/xray': typeof AuthenticatedXrayRoute
  '/api/founder-transcribe': typeof ApiFounderTranscribeRoute
  '/r/$reportId': typeof RReportIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/product-strategy/$strategyId': typeof AuthenticatedProductStrategyStrategyIdRoute
  '/_authenticated/report/$reportId': typeof AuthenticatedReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/founder-gps'
    | '/founder-readiness'
    | '/history'
    | '/premium'
    | '/product-strategy'
    | '/profile'
    | '/settings'
    | '/xray'
    | '/api/founder-transcribe'
    | '/r/$reportId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/product-strategy/$strategyId'
    | '/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/founder-gps'
    | '/founder-readiness'
    | '/history'
    | '/premium'
    | '/product-strategy'
    | '/profile'
    | '/settings'
    | '/xray'
    | '/api/founder-transcribe'
    | '/r/$reportId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/product-strategy/$strategyId'
    | '/report/$reportId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/founder-gps'
    | '/_authenticated/founder-readiness'
    | '/_authenticated/history'
    | '/_authenticated/premium'
    | '/_authenticated/product-strategy'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/xray'
    | '/api/founder-transcribe'
    | '/r/$reportId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/product-strategy/$strategyId'
    | '/_authenticated/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiFounderTranscribeRoute: typeof ApiFounderTranscribeRoute
  RReportIdRoute: typeof RReportIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$reportId': {
      id: '/r/$reportId'
      path: '/r/$reportId'
      fullPath: '/r/$reportId'
      preLoaderRoute: typeof RReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founder-transcribe': {
      id: '/api/founder-transcribe'
      path: '/api/founder-transcribe'
      fullPath: '/api/founder-transcribe'
      preLoaderRoute: typeof ApiFounderTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/xray': {
      id: '/_authenticated/xray'
      path: '/xray'
      fullPath: '/xray'
      preLoaderRoute: typeof AuthenticatedXrayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-strategy': {
      id: '/_authenticated/product-strategy'
      path: '/product-strategy'
      fullPath: '/product-strategy'
      preLoaderRoute: typeof AuthenticatedProductStrategyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder-readiness': {
      id: '/_authenticated/founder-readiness'
      path: '/founder-readiness'
      fullPath: '/founder-readiness'
      preLoaderRoute: typeof AuthenticatedFounderReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder-gps': {
      id: '/_authenticated/founder-gps'
      path: '/founder-gps'
      fullPath: '/founder-gps'
      preLoaderRoute: typeof AuthenticatedFounderGpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/$reportId': {
      id: '/_authenticated/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof AuthenticatedReportReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-strategy/$strategyId': {
      id: '/_authenticated/product-strategy/$strategyId'
      path: '/$strategyId'
      fullPath: '/product-strategy/$strategyId'
      preLoaderRoute: typeof AuthenticatedProductStrategyStrategyIdRouteImport
      parentRoute: typeof AuthenticatedProductStrategyRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProductStrategyRouteChildren {
  AuthenticatedProductStrategyStrategyIdRoute: typeof AuthenticatedProductStrategyStrategyIdRoute
}

const AuthenticatedProductStrategyRouteChildren: AuthenticatedProductStrategyRouteChildren =
  {
    AuthenticatedProductStrategyStrategyIdRoute:
      AuthenticatedProductStrategyStrategyIdRoute,
  }

const AuthenticatedProductStrategyRouteWithChildren =
  AuthenticatedProductStrategyRoute._addFileChildren(
    AuthenticatedProductStrategyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFounderGpsRoute: typeof AuthenticatedFounderGpsRoute
  AuthenticatedFounderReadinessRoute: typeof AuthenticatedFounderReadinessRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProductStrategyRoute: typeof AuthenticatedProductStrategyRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedXrayRoute: typeof AuthenticatedXrayRoute
  AuthenticatedReportReportIdRoute: typeof AuthenticatedReportReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFounderGpsRoute: AuthenticatedFounderGpsRoute,
  AuthenticatedFounderReadinessRoute: AuthenticatedFounderReadinessRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProductStrategyRoute:
    AuthenticatedProductStrategyRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedXrayRoute: AuthenticatedXrayRoute,
  AuthenticatedReportReportIdRoute: AuthenticatedReportReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiFounderTranscribeRoute: ApiFounderTranscribeRoute,
  RReportIdRoute: RReportIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
